---
# Source: app/templates/database-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-python-0
  name: postgres-python-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
# Source: app/templates/anythink-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: anythink-backend
  name: anythink-backend
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: anythink-backend
---
# Source: app/templates/anythink-frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: anythink-frontend
  name: anythink-frontend
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    app: anythink-frontend
---
# Source: app/templates/database-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-python
  name: postgres-python
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-python
---
# Source: app/templates/anythink-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anythink-backend
  name: anythink-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythink-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anythink-backend
        date: "1672654365"
    spec:
      containers:
        - args:
            - sh
            - -c
            - "yarn seeds && yarn start"
          env:
            - name: MONGODB_URI
              value: "postgresql://postgres-python:5432/anythink-market"
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3000"
          image: "498915426792.dkr.ecr.us-east-2.amazonaws.com/anythink-backend:latest"
          imagePullPolicy: Always
          name: anythink-backend
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
# Source: app/templates/anythink-frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anythink-frontend
  name: anythink-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythink-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anythink-frontend
        date: "1672654365"
    spec:
      containers:
        - args:
            - sh
            - -c
            - yarn start
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3001"
            - name: REACT_APP_BACKEND_URL
              value: https://default-api.prod.anythink.market
          image: "498915426792.dkr.ecr.us-east-2.amazonaws.com/anythink-frontend:latest"
          imagePullPolicy: Always
          name: anythink-frontend
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 600m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
---
# Source: app/templates/database-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-python
  name: postgres-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-python
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-python
    spec:
      containers:
        - image: "postgres:latest"
          name: postgres-python
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: anythink-market
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5433
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: postgres-python-0
      restartPolicy: Always
      volumes:
        - name: postgres-python-0
          persistentVolumeClaim:
            claimName: postgres-python-0
